FORM golang:1.14.3 AS build

COPY ./* /go/src/github.com/HYmian/

RUN go build -mod vendor -v

FROM centos:7.6.1810

WORKDIR /var/local/bin

ADD --from=build gin-sample .

CMD ["./gin-sample", "-logtostderr", "-v", "2"]
