FORM golang:1.14.3 AS build

WORKDIR /go/src/github.com/HYmian/gin-sample

ADD ./ ./

RUN go install -mod vendor -v

FROM centos:7.6.1810

WORKDIR /var/local/bin

ADD --from=build gin-sample .

CMD ["./gin-sample", "-logtostderr", "-v", "2"]
